import type { Metadata } from "next";
import "./globals.css";
import ThemeToggle from "@/components/general/theme-toggle";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className="antialiased flex items-center justify-center">
        {children}
        <ThemeToggle />
      </body>
    </html>
  );
};

export default RootLayout;
